# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '04880846-0c6d-477c-ba5d-41a07901d294'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Saturday01Aug2020'
    location: 'Australia Central'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName thursday06082020 -linkedTemplateUri https://raw.githubusercontent.com/armando-rubiano/saturday01aug-repo/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'AzureTutorial'
